let plant_data = [
  {
    image: "https://iili.io/HNOJiVn.jpg",
    price: "200",
    name: "Pinkrose_Plant",
    ratings: "4",
    image_1: "https://iili.io/HNOdHx9.jpg",
    image_2: "https://iili.io/HNOdFlj.jpg",
    image_3: "https://iili.io/HNOdBRV.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti.",
    Type_of_plant: "Flower",
    Suitable_Location: "Full sun.",
    Container_Type: "Pot With drainage hole",
    Height: " 1 feet",
    Brand: "Damask Rose",
    Planting_Season: "September to October.",
    Hybrid: "CurlyPink",
    status: false,
  },
  {
    image: "https://iili.io/HNOKOYb.jpg",
    price: "359",
    name: "Dieffenbachia",
    ratings: "6",
    image_1: "https://iili.io/HNOqRgn.jpg",
    image_2: "https://iili.io/HNOqRgn.jpg",
    image_3: "https://iili.io/HNOoMjj.jpg",
    about:
      " Dieffenbachia helps remove toxins from the air, including xylene, to offer you and your family members clean breathing air in your home.",
    Type_of_plant: "Foliage",
    Suitable_Location: "Indoor",
    Container_Type: "Pot",
    Height: " 300 mm",
    Brand: " Go4plants",
    Planting_Season: "early spring",
    Hybrid: "No",
    status: true,
  },
  {
    image: "https://iili.io/HNOTF9t.webp",
    price: "140",
    name: "Miniorange_plant",
    ratings: "6",
    image_1: "https://iili.io/HNOTfNn.jpg",
    image_2: "https://iili.io/HNOTAH7.jpg",
    image_3: "https://iili.io/HNOTaob.jpg",
    about:
      "Low Maintenance. It Requires Less Care,so it can even Be Grown by your Kids. Your Kids Will Be Delighted to Have a Cup of Juice from The Plant they have Planted and Cherished.",
    Plant_Name: "Miniorange_plant",
    Type_of_plant: "Fruit",
    Suitable_Location: " Outdoor",
    Container_Type: "Plastic Bag",
    Height: " 300 mm",
    Brand: "Dwarf Orange tree",
    Planting_Season: "July to September.",
    table_Plantname: "Miniorange_plant",
    Hybrid: "Kamkot lemon",
    status: true,
  },
  {
    image: "https://iili.io/HNNpjrQ.jpg",
    price: "186",
    name: "Hibiscus_plant",
    ratings: "5",
    image_1: "https://iili.io/HNNmEiv.jpg",
    image_2: "https://iili.io/HNNmVlp.jpg",
    image_3: "https://iili.io/HNNmhJI.jpg",
    about: "One Healthy Live Plant In Pot\\nLow maintenance home plant.",
    Type_of_plant: "Flower",
    Suitable_Location: "Indoor",
    Container_Type: "Pot",
    Height: "150 mm",
    Brand: "Starlink",
    Planting_Season: "Autumn",
    Hybrid: "No",
    Category: "Plant",
    status: true,
  },
  {
    image: "https://iili.io/HwCIiBa.jpg",
    price: "175",
    name: "Middlemist_Red",
    ratings: "6",
    image_1: "https://iili.io/HwazC3Q.jpg",
    image_2: "https://iili.io/HwaISJp.jpg",
    image_3: "https://iili.io/HwauwKJ.jpg",
    about:
      "You can only see middlemist red flower in New Zealand garden and green house garden of United Kingdom. ",
    Type_of_plant: "Flower",
    Suitable_Location: "Outdoor",
    Container_Type: "Pot",
    Height: " 6 to 12 feet.",
    Brand: " E Garden",
    Planting_Season: "Autumn",
    Hybrid: "No",
    Category: "Plant",
    status: true,
  },
  {
    image: "https://iili.io/HNOJiVn.jpg",
    price: "200",
    name: "Pinkrose_Plant",
    ratings: "4",
    image_1: "https://iili.io/HNOdHx9.jpg",
    image_2: "https://iili.io/HNOdFlj.jpg",
    image_3: "https://iili.io/HNOdBRV.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti.",
    Type_of_plant: "Flower",
    Suitable_Location: "Full sun",
    Container_Type: "Pot With drainage hole",
    Height: "1 feet.",
    Brand: "Damask Rose",
    Planting_Season: "September to October",
    Hybrid: "CurlyPink",
    Category: "Plant",
    status: false,
  },
  {
    image: "https://iili.io/HNOJiVn.jpg",
    price: "200",
    name: "Pinkrose_Plant",
    ratings: "4",
    image_1: "https://iili.io/HNOdHx9.jpg",
    image_2: "https://iili.io/HNOdFlj.jpg",
    image_3: "https://iili.io/HNOdBRV.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti.",
    Type_of_plant: "Flower",
    Suitable_Location: "Full sun",
    Container_Type: "Pot With drainage hole",
    Height: "1 feet.",
    Brand: "Damask Rose",
    Planting_Season: "September to October",
    Hybrid: "CurlyPink",
    Category: "Plant",
    status: false,
  },
  {
    image: "https://iili.io/HNOJiVn.jpg",
    price: "200",
    name: "Pinkrose Plant",
    ratings: "5",
    image_1: "https://iili.io/HNOdHx9.jpg",
    image_2: "https://iili.io/HNOdFlj.jpg",
    image_3: "https://iili.io/HNOdBRV.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti",
    Type_of_plant: "Flower",
    Suitable_Location: "Full sun",
    Container_Type: "Pot With drainage hole",
    Height: "1 feet",
    Brand: "Damask Rose",
    Planting_Season: "September to October",
    Hybrid: "CurlyPink",
    Category: "Plant",
  },
  {
    image: "https://iili.io/HNOJiVn.jpg",
    price: "200",
    name: "Pinkrose Plant",
    ratings: "5",
    image_1: "https://iili.io/HNOdHx9.jpg",
    image_2: "https://iili.io/HNOdFlj.jpg",
    image_3: "https://iili.io/HNOdBRV.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti",
    Type_of_plant: "Flower",
    Suitable_Location: "Full sun",
    Container_Type: "Pot With drainage hole",
    Height: "1 feet",
    Brand: "Damask Rose",
    Planting_Season: "September to October",
    Hybrid: "CurlyPink",
    Category: "Plant",
  },
  {
    image: "https://iili.io/HNOJiVn.jpg",
    price: "180",
    name: "Pinkrose plant",
    ratings: "4",
    image_1: "https://iili.io/HNOdHx9.jpg",
    image_2: 'https://iili.io/HNOdFlj.jpg"',
    image_3: "https://iili.io/HNOdBRV.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti",
    Type_of_plant: "Flower",
    Suitable_Location: "full sun",
    Container_Type: "Pot With drainage hole",
    Height: "1 feet",
    Brand: "Damask Rose",
    Planting_Season: "September to October",
    Hybrid: "CurlyPink",
    Category: "Plant",
    status: true,
  },
  {
    image: "https://iili.io/H8MPnmN.jpg",
    price: "221",
    name: "Money tree",
    ratings: "4",
    image_1: "https://iili.io/H8M6XON.jpg",
    image_2: "https://iili.io/H8MP72f.webp",
    image_3: "https://iili.io/H8M6Pz7.jpg",
    about:
      "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti",
    Type_of_plant: "tree",
    Suitable_Location: "indoor ",
    Container_Type: "Pot With drainage hole",
    Height: " grow to be up to 7 feet/  2-4 inches",
    Brand: "The nursery",
    Planting_Season: "Spring, Summer",
    Hybrid: "No",
    Category: "Plant",
    status: true,
  },
  {
    image: "https://iili.io/H8MmLua.webp",
    price: "160",
    name: " Anthurium Plant",
    ratings: "4",
    image_1: "https://iili.io/H8Mmg6B.jpg",
    image_2: "https://iili.io/H8Mpd9n.jpg",
    image_3: "https://iili.io/H8Mpif2.jpg ",
    about:
      "\nRed Anthurium or Flamingo Lily is great for air filtering; it is on NASA's clean air study list. Bonus: This flowering plant has beautiful red, heart-shaped blooms making this plant perfect for your love corner",
    Type_of_plant: "Succulent",
    Suitable_Location: "Indoor",
    Container_Type: " Grow Bag",
    Height: "190 mm",
    Brand: " sivsankar enterprises",
    Planting_Season: " Autumn",
    Hybrid: " Yes",
    Category: "Plant",
    status: true,
  },
  {
    image: "https://iili.io/H8VJXet.jpg",
    price: "180",
    name: "Pomegranate Plant",
    ratings: "5",
    image_1: "https://iili.io/H8Vdzjn.webp",
    image_2: "https://iili.io/H8VdYa2.jpg",
    image_3: "https://iili.io/H8Vd0u9.jpg",
    about:
      "Regular consumption of pomegranate helps in improving gut health, digestion, and keep bowel diseases at bay. 3. Adding it in your daily diet will also assist in improvising and regulating the flow of blood",
    Type_of_plant: " Fruit",
    Suitable_Location: " Outdoor",
    Container_Type: "Grow Bag",
    Height: "200 mm",
    Brand: "Earth Plant Farm",
    Planting_Season: "spring (February-March) and July-August in sub-tropical ",
    Hybrid: "No",
    Category: "Plant",
    status: true,
  },
  {
    image: "https://iili.io/H8V3vEJ.webp",
    price: "258",
    name: "Gerbera Plant( Red) ",
    ratings: "4",
    image_1: "https://iili.io/H8VFCvV.jpg",
    image_2: "https://iili.io/H8VFzj1.jpg",
    image_3: "https://iili.io/H8VF4Fj.jpg",
    about:
      "hese flowers are generally used as a decorative cut flower for bouquets but are also in flower beds. These daisies come in many vibrant colors including red, orange, yellow, pink, white and cream.",
    Type_of_plant: "flower",
    Suitable_Location: " indoor",
    Container_Type:
      " 1/3 pot with well drained soil which is rich in organic content",
    Height: "15 to 45 cm",
    Brand: "The nursery",
    Planting_Season: "spring",
    Hybrid: "No",
    Category: "Plant",
    status: false,
  },
  {
    image: "https://iili.io/H8V3vEJ.webp",
    price: "258",
    name: "Gerbera red Plant",
    ratings: "4",
    image_1: "https://iili.io/H8VFzj1.jpg",
    image_2: "https://iili.io/H8VFCvV.jpg",
    image_3: "https://iili.io/H8VF4Fj.jpg",
    about:
      "hese flowers are generally used as a decorative cut flower for bouquets but are also in flower beds. These daisies come in many vibrant colors including red, orange, yellow, pink, white and cream.",
    Type_of_plant: "flower",
    Suitable_Location: " indoor",
    Container_Type:
      " 1/3 pot with well drained soil which is rich in organic content",
    Height: "15 to 45 cm",
    Brand: "The nursery",
    Planting_Season: "spring",
    Hybrid: "No",
    status: true,
  },
];

if (localStorage.getItem("create_plant")) {
} else {
  localStorage.setItem("create_plant", JSON.stringify(plant_data));
}

if (localStorage.getItem("seed_details")) {
} else {
  localStorage.setItem(
    "seed_details",
    JSON.stringify([
      {
        image: "https://iili.io/HNgR6Ft.jpg",
        price: "195.99",
        name: "Blacktomato_seeds",
        ratings: "4",
        image_1: "https://iili.io/HNgBp7p.jpg",
        image_2: "https://iili.io/HNgC2Qn.jpg",
        image_3: "https://iili.io/HNgCf4f.jpg",
        about:
          "Green Gallery Provide Best Quality Vegetables Seeds.Tomatoes Are The Fruit Of The Tomato Plant.Tomatoes Are The State Vegetable Of New Jersey",
        Type_of_plant: "seeds",
        Suitable_Location: "Full sun.",
        Container_Type: "Pot or in land",
        Height: "6 inches",
        Brand: "Green Gallery",
        Planting_Season: "Spring",
        Hybrid: "No",
        Category: "Seed",
        status: true,
      },
      {
        image: "https://iili.io/HNgayzb.webp",
        price: "45.25",
        name: "Bean_seeds",
        ratings: "5",
        image_1: "https://iili.io/HNglZNe.jpg",
        image_2: "https://iili.io/HNglpix.jpg",
        image_3: "https://iili.io/HNg0KDg.jpg",
        about:
          "Bean seeds are rich sources of fiber and important vitamins and minerals. They're also great sources of vegetarian protein.",
        Type_of_plant: "seeds",
        Suitable_Location: "soils that are well-drained and fertile",
        Container_Type: " 8 to 10-inch containers",
        Height: "reaching about two-feet tall",
        Brand: "Beans",
        Planting_Season: "March or April",
        Hybrid: "No",
        Category: "Seed",
        status: true,
      },
      {
        image: "https://iili.io/HNrK3a2.webp",
        price: "200",
        name: "Soakchia_seeds",
        ratings: "5",
        image_1: "https://iili.io/HNrKkPf.webp",
        image_2: "https://iili.io/HNrKtKx.jpg",
        image_3: "https://iili.io/HNrfCHN.jpg",
        about:
          "Soakchia seeds and contain a lot of water.Eating them soaked in water may help promotes hydration, healthy digestion and lower hunger.",
        Type_of_plant: "seeds",
        Suitable_Location: "Full sun.",
        Container_Type: "box or any pot.",
        Height: "2 millimetres ",
        Brand: "Agrofoods",
        Planting_Season: "Grows in all seasons",
        Hybrid: "No",
        Category: "Seed",
        status: true,
      },
      {
        image: "https://iili.io/HNLUJDB.webp",
        price: "85",
        name: "Cucamelon_seeds",
        ratings: "5",
        image_1: "https://iili.io/HNLUFiF.webp",
        image_2: "https://iili.io/HNLUTxI.jpg",
        image_3: "https://iili.io/HNLUcJf.jpg",
        about:
          "Cucamelon seeds produce vines that could be mistaken for regular cucumber plants.",
        Type_of_plant: "Vegetable",
        Suitable_Location: " Indoor, Outdoor",
        Container_Type: "garden beds",
        Height: "1 ft. tall, up to 10 ft. wide",
        Brand: "cucumber",
        Planting_Season: "April and May",
        Hybrid: "cucumber",
        Category: "Seed",
        status: true,
      },
    ])
  );
}

if (localStorage.getItem("review_array")) {
} else {
  localStorage.setItem(
    "review_array",
    JSON.stringify([
      {
        name: "Steffy_Alexander",
        rating: "5",
        review:
          "Great selection of plants and shrubs very reasonable prices and helpful staff,buy my plants here every year",
      },

      {
        name: "Barath",
        rating: "5",
        review:
          "Great selection of perennials and other plants\nTop nursery for plant lovers, free from all the furniture clothing and other grot found in large garden centres. This is the place to go when you want to buy plants and get advice about growing them.",
      },
    ])
  );
}
