if (localStorage.getItem("create_plant")) {
  //   return;
} else {
  localStorage.setItem(
    "create_plant",
    JSON.stringify([
      {
        image: "https://iili.io/HNOJiVn.jpg",
        price: "349",
        name: "Pinkrose_Plant",
        ratings: "4",
        image_1: "https://iili.io/HNOdHx9.jpg",
        image_2: "https://iili.io/HNOdFlj.jpg",
        image_3: "https://iili.io/HNOdBRV.jpg",
        about:
          "The history of pink roses begins around 35 million years ago, when the first trace of a rose was found in fossils. The cultivation of garden roses originated in China about 5,000 years ago. During the Roman Empire, roses were used as medicine, perfume and confetti.",
        Plant_Name: "Pinkrose_Plant",
        Type_of_plant: "Flower",
        Suitable_Location: "Full sun.",
        Container_Type: "Pot With drainage hole",
        Height: " 1.5 feet",
        Brand: "Damask Rose",
        Planting_Season: "September to October.",
        table_Plantname: "Pinkrose_Plant",
        Hybrid: " Curly Pink",
      },
      {
        image: "https://iili.io/HNOKOYb.jpg",
        price: "359",
        name: "Dieffenbachia",
        ratings: "6",
        image_1: "https://iili.io/HNOqRgn.jpg",
        image_2: "https://iili.io/HNOqRgn.jpg",
        image_3: "https://iili.io/HNOoMjj.jpg",
        about:
          " Dieffenbachia helps remove toxins from the air, including xylene, to offer you and your family members clean breathing air in your home.",
        Plant_Name: "Dieffenbachia",
        Type_of_plant: "Foliage",
        Suitable_Location: "Indoor",
        Container_Type: "Pot",
        Height: " 150 mm",
        Brand: " go4plants",
        Planting_Season: " early spring",
        table_Plantname: "Dieffenbachia",
        Hybrid: "No",
      },
      {
        image: "https://iili.io/HNOTF9t.webp",
        price: "140",
        name: "Miniorange_plant",
        ratings: "6",
        image_1: "https://iili.io/HNOTfNn.jpg",
        image_2: "https://iili.io/HNOTAH7.jpg",
        image_3: "https://iili.io/HNOTaob.jpg",
        about:
          "Low Maintenance. It Requires Less Care,so it can even Be Grown by your Kids. Your Kids Will Be Delighted to Have a Cup of Juice from The Plant they have Planted and Cherished.",
        Plant_Name: "Miniorange_plant",
        Type_of_plant: "Fruit",
        Suitable_Location: " Outdoor",
        Container_Type: "Plastic Bag",
        Height: " 300 mm",
        Brand: "Dwarf Orange tree",
        Planting_Season: "July to September.",
        table_Plantname: "Miniorange_plant",
        Hybrid: "Kamkot lemon",
      },
      {
        image: "https://iili.io/HNNpjrQ.jpg",
        price: "186",
        name: "Hibiscus_plant",
        ratings: "5",
        image_1: "https://iili.io/HNNmEiv.jpg",
        image_2: "https://iili.io/HNNmVlp.jpg",
        image_3: "https://iili.io/HNNmhJI.jpg",
        about: "One Healthy Live Plant In Pot\\nLow maintenance home plant.",
        Type_of_plant: "Flower",
        Suitable_Location: "Indoor",
        Container_Type: "Pot",
        Height: "150 mm",
        Brand: "Starlink",
        Planting_Season: "Autumn",
        Hybrid: "No",
        Category: "Plant",
      },
      {
        image: "https://iili.io/HwCIiBa.jpg",
        price: "175",
        name: "Middlemist_Red",
        ratings: "6",
        image_1: "https://iili.io/HwazC3Q.jpg",
        image_2: "https://iili.io/HwaISJp.jpg",
        image_3: "https://iili.io/HwauwKJ.jpg",
        about:
          "You can only see middlemist red flower in New Zealand garden and green house garden of United Kingdom. ",
        Type_of_plant: "Flower",
        Suitable_Location: "Outdoor",
        Container_Type: "Pot",
        Height: " 6 to 12 feet.",
        Brand: " E Garden",
        Planting_Season: "Autumn",
        Hybrid: "No",
        Category: "Plant",
      },
    ])
  );
}

if (localStorage.getItem("seed_details")) {
} else {
  localStorage.setItem(
    "seed_details",
    JSON.stringify([
      {
        image: "https://iili.io/HNgR6Ft.jpg",
        price: "195.99",
        name: "Blacktomato_seeds",
        ratings: "4",
        image_1: "https://iili.io/HNgBp7p.jpg",
        image_2: "https://iili.io/HNgC2Qn.jpg",
        image_3: "https://iili.io/HNgCf4f.jpg",
        about:
          "Green Gallery Provide Best Quality Vegetables Seeds.Tomatoes Are The Fruit Of The Tomato Plant.Tomatoes Are The State Vegetable Of New Jersey",
        Type_of_plant: "seeds",
        Suitable_Location: "Full sun.",
        Container_Type: "Pot or in land",
        Height: "6 inches",
        Brand: "Green Gallery",
        Planting_Season: "Spring",
        Hybrid: "No",
        Category: "Seed",
      },
      {
        image: "https://iili.io/HNgayzb.webp",
        price: "45.25",
        name: "Bean_seeds",
        ratings: "5",
        image_1: "https://iili.io/HNglZNe.jpg",
        image_2: "https://iili.io/HNglpix.jpg",
        image_3: "https://iili.io/HNg0KDg.jpg",
        about:
          "Bean seeds are rich sources of fiber and important vitamins and minerals. They're also great sources of vegetarian protein.",
        Type_of_plant: "seeds",
        Suitable_Location: "soils that are well-drained and fertile",
        Container_Type: " 8 to 10-inch containers",
        Height: "reaching about two-feet tall",
        Brand: "Beans",
        Planting_Season: "March or April",
        Hybrid: "No",
        Category: "Seed",
      },
    ])
  );
}
